<a href="https://colab.research.google.com/github/farelagustin/2026_kecerdasan_buatan/blob/main/Jobsheet_08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LATIHAN

Data Preparation dengan One Hot Encoding

In [ ]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# 1. Membuat dataframe contoh berisi data gender
gender = ['perempuan', 'laki-laki', 'laki-laki', 'perempuan', 'perempuan']
df = pd.DataFrame({'gender': gender})

# 2. Membuat instance dan melakukan One Hot Encoding
encoder = OneHotEncoder()
encoded_df = pd.DataFrame(
    encoder.fit_transform(df[['gender']]).toarray(),
    columns=encoder.get_feature_names_out(['gender']))

# 3. Menggabungkan data frame awal dengan hasil encode
df_encoded = pd.concat([df, encoded_df], axis=1)
print(df_encoded)

      gender  gender_laki-laki  gender_perempuan
0  perempuan               0.0               1.0
1  laki-laki               1.0               0.0
2  laki-laki               1.0               0.0
3  perempuan               0.0               1.0
4  perempuan               0.0               1.0

Data Preparation dengan Outlier Removal

In [ ]:
import pandas as pd
import numpy as np

# 1. Membuat data frame contoh yang memiliki outlier (nilai 500)
df_outlier = pd.DataFrame({
    'A': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'B': [15, 20, 25, 30, 35, 40, 45, 50, 55, 500]
})

# 2. Mencari nilai z-score absolut pada kolom B
z_scores = np.abs((df_outlier['B'] - df_outlier['B'].mean()) / df_outlier['B'].std())

# 3. Menghilangkan data yang memiliki z-score >= 3 (outlier)
df_clean = df_outlier.loc[round(z_scores) < 3]
print(df_clean)

   A   B
0  1  15
1  2  20
2  3  25
3  4  30
4  5  35
5  6  40
6  7  45
7  8  50
8  9  55

Data Preparation dengan Normalization (MinMaxScaler)

In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# 1. Membuat dataframe contoh
df_norm = pd.DataFrame({
    'Nama': ['Andi', 'Budi', 'Cindy', 'Diana', 'Eka', 'lala'],
    'Gaji': [3000000, 5000000, 7000000, 9000000, 11000000, 9000000],
    'Umur': [25, 30, 35, 40, 45, 30]
})

# 2. Normalisasi menggunakan MinMaxScaler
scaler_minmax = MinMaxScaler()
df_norm[['Gaji', 'Umur']] = scaler_minmax.fit_transform(df_norm[['Gaji', 'Umur']])
print(df_norm)

    Nama  Gaji  Umur
0   Andi  0.00  0.00
1   Budi  0.25  0.25
2  Cindy  0.50  0.50
3  Diana  0.75  0.75
4    Eka  1.00  1.00
5   lala  0.75  0.25

Data Preparation dengan Standarization (StandardScaler)

In [ ]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

# 1. Menggunakan data frame yang sama
df_std = pd.DataFrame({
    'Nama': ['Andi', 'Budi', 'Cindy', 'Diana', 'Eka', 'lala'],
    'Gaji': [3000000, 5000000, 7000000, 9000000, 11000000, 9000000],
    'Umur': [25, 30, 35, 40, 45, 30]
})

# 2. Standarisasi menggunakan StandardScaler (Z-Score scale)
scaler_std = StandardScaler()
df_std[['Gaji', 'Umur']] = scaler_std.fit_transform(df_std[['Gaji', 'Umur']])
print(df_std)

    Nama      Gaji      Umur
0   Andi -1.612452 -1.364382
1   Budi -0.868243 -0.620174
2  Cindy -0.124035  0.124035
3  Diana  0.620174  0.868243
4    Eka  1.364382  1.612452
5   lala  0.620174 -0.620174

Pembagian Dataset & Cross Validation

A. Contoh menggunakan `heart.csv`

In [ ]:
from sklearn.model_selection import train_test_split
import pandas as pd

# Pastikan kamu sudah mengunduh file 'heart.csv' jika ingin menjalankan baris ini
df_heart = pd.read_csv('https://raw.githubusercontent.com/farelagustin/LatihanEDA/refs/heads/main/heart.csv')

# Mengambil 13 kolom pertama sebagai fitur (X) dan kolom terakhir sebagai label/target (y)
X = df_heart.iloc[:, :13].values
y = df_heart.iloc[:, -1].values

# Membagi menjadi data training dan testing (80:20)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print('Ukuran data latih:', X_train.shape)
print('Ukuran data uji:', X_test.shape)

Ukuran data latih: (231, 13)
Ukuran data uji: (58, 13)

B. Cross Validation

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()
# Melakukan 5-fold cross validation
scores = cross_val_score(dt, X, y, cv=5)

print('Hasil cross validation:', scores)

Hasil cross validation: [0.74137931 0.79310345 0.82758621 0.70689655 0.66666667]

# PRAKTIKUM

Langkah awal adalah memanggil library yang dibutuhkan dan membaca dataset `iklan_sosmed.csv`. Kita juga akan menghapus kolom ID karena kolom tersebut hanya berisi ID unik pelanggan dan tidak memiliki pengaruh korelasi terhadap prediksi machine learning.

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder, StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split

# 1. Membaca dataset iklan sosmed
df = pd.read_csv('https://raw.githubusercontent.com/farelagustin/LatihanEDA/refs/heads/main/iklan_sosmed1.csv', sep=';')
# df = pd.read_csv(url, sep=';')

# 2. Menampilkan informasi awal data
print("--- Informasi Awal Dataset ---")
print(df.info())


# 3. Menghapus kolom 'User ID' jika ada (karena tidak diperlukan untuk modeling)
if 'ID' in df.columns:
    df = df.drop(columns=['ID'])

print("\n5 Data Teratas:")
print(df.head())

--- Informasi Awal Dataset ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             400 non-null    int64
 1   Jenis_Kelamin  400 non-null    object
 2   Umur           400 non-null    int64
 3   Gaji           400 non-null    int64
 4   Transaksi      400 non-null    int64
dtypes: int64(4), object(1)
memory usage: 15.8+ KB
None

5 Data Teratas:
  Jenis_Kelamin  Umur        Gaji  Transaksi
0          Pria    19   285000000          0
1          Pria    35   300000000          0
2        Wanita    26   645000000          0
3        Wanita    27   855000000          0
4          Pria    19  1140000000          0

Data Preparation dengan One Hot Encoding

Di tahap ini, kita mengubah fitur kategorikal seperti kolom Jenis_Kelamin (Laki-laki/Perempuan) menjadi bentuk angka biner (0 dan 1).

In [ ]:
# Membuat instance OneHotEncoder
encoder = OneHotEncoder(sparse_output=False) # sparse_output=False agar langsung menghasilkan array

# Melakukan encoding pada kolom 'Jenis_Kelamin'
Jenis_Kelamin_encoded = encoder.fit_transform(df[['Jenis_Kelamin']])

# Membuat dataframe baru dari hasil encoding dengan nama kolom yang sesuai
Jenis_Kelamin_df = pd.DataFrame(Jenis_Kelamin_encoded, columns=encoder.get_feature_names_out(['Jenis_Kelamin']))

# Menggabungkan kembali dengan dataframe utama dan menghapus kolom 'Jenis_Kelamin' yang lama
df = pd.concat([df.drop(columns=['Jenis_Kelamin']), Jenis_Kelamin_df], axis=1)

print("--- Hasil Setelah One Hot Encoding ---")
print(df.head())

--- Hasil Setelah One Hot Encoding ---
   Umur        Gaji  Transaksi  Jenis_Kelamin_Pria  Jenis_Kelamin_Wanita
0    19   285000000          0                 1.0                   0.0
1    35   300000000          0                 1.0                   0.0
2    26   645000000          0                 0.0                   1.0
3    27   855000000          0                 0.0                   1.0
4    19  1140000000          0                 1.0                   0.0

Data Preparation dengan Outlier Removal (Z-Score)

Kita bersihkan data dari nilai-nilai ekstrem (pencilan) menggunakan metode Z-Score pada kolom numerik, yaitu Gaji dan Umur.

In [ ]:
# Mencari nilai z-score absolut untuk kolom numerik 'Gaji'
z_scores_Gaji = np.abs((df['Gaji'] - df['Gaji'].mean()) / df['Gaji'].std())

# Menghilangkan data point yang memiliki z-score lebih besar atau sama dengan 3
df_clean = df.loc[z_scores_Gaji < 3].reset_index(drop=True)

print("--- Hasil Setelah Outlier Removal ---")
print(f"Jumlah data sebelum dibersihkan: {len(df)}")
print(f"Jumlah data setelah dibersihkan: {len(df_clean)}")

--- Hasil Setelah Outlier Removal ---
Jumlah data sebelum dibersihkan: 400
Jumlah data setelah dibersihkan: 400

In [ ]:
# Mencari nilai z-score absolut untuk kolom numerik 'Umur'
z_scores_Umur = np.abs((df['Umur'] - df['Umur'].mean()) / df['Umur'].std())

# Menghilangkan data point yang memiliki z-score lebih besar atau sama dengan 3
df_clean = df.loc[z_scores_Umur < 3].reset_index(drop=True)

print("--- Hasil Setelah Outlier Removal ---")
print(f"Jumlah data sebelum dibersihkan: {len(df)}")
print(f"Jumlah data setelah dibersihkan: {len(df_clean)}")

--- Hasil Setelah Outlier Removal ---
Jumlah data sebelum dibersihkan: 400
Jumlah data setelah dibersihkan: 400

Feature Scaling (Standardization / Normalization)

Standardization

In [ ]:
# Membuat instance dari StandardScaler
scaler = StandardScaler()

# Menerapkan standardisasi pada fitur numerik 'Umur' dan 'Gaji'
df_clean[['Umur', 'Gaji']] = scaler.fit_transform(df_clean[['Umur', 'Gaji']])

print("--- Hasil Setelah Feature Scaling (Standardization) ---")
print(df_clean.head())

--- Hasil Setelah Feature Scaling (Standardization) ---
       Umur      Gaji  Transaksi  Jenis_Kelamin_Pria  Jenis_Kelamin_Wanita
0 -1.781797 -1.490046          0                 1.0                   0.0
1 -0.253587 -1.460681          0                 1.0                   0.0
2 -1.113206 -0.785290          0                 0.0                   1.0
3 -1.017692 -0.374182          0                 0.0                   1.0
4 -1.781797  0.183751          0                 1.0                   0.0

Normalization

In [ ]:
# Membuat instance dari StandardScaler
scaler = MinMaxScaler()

# Menerapkan normalisasi pada fitur numerik 'Umur' dan 'Gaji'
df_clean[['Umur', 'Gaji']] = scaler.fit_transform(df_clean[['Umur', 'Gaji']])

print("--- Hasil Setelah Feature Scaling (Normalization) ---")
print(df_clean.head())

--- Hasil Setelah Feature Scaling (Normalization) ---
       Umur      Gaji  Transaksi  Jenis_Kelamin_Pria  Jenis_Kelamin_Wanita
0  0.023810  0.029630          0                 1.0                   0.0
1  0.404762  0.037037          0                 1.0                   0.0
2  0.190476  0.207407          0                 0.0                   1.0
3  0.214286  0.311111          0                 0.0                   1.0
4  0.023810  0.451852          0                 1.0                   0.0

Mengambil Dataset

In [ ]:
# Melihat korelasi antar kolom
df_clean.corr()

,Umur,Gaji,Transaksi,Jenis_Kelamin_Pria,Jenis_Kelamin_Wanita
Umur,1.000000,0.155238,0.622454,-0.073741,0.073741
Gaji,0.155238,1.000000,0.362083,-0.060435,0.060435
Transaksi,0.622454,0.362083,1.000000,-0.042469,0.042469
Jenis_Kelamin_Pria,-0.073741,-0.060435,-0.042469,1.000000,-1.000000
Jenis_Kelamin_Wanita,0.073741,0.060435,0.042469,-1.000000,1.000000

In [ ]:
# Mengambil Umur dan Gaji sebagai Variabel Data dan Transaksi sebagai Variabel Label
X = df.iloc[:,0:-3]
y = df.iloc[:, -3]

In [ ]:
# Bagi data menjadi 80% data latih dan 20% ata uji
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
y_train

3      0
18     1
202    1
250    0
274    1
      ..
71     0
106    0
270    0
348    0
102    0
Name: Transaksi, Length: 320, dtype: int64

In [ ]:
# normalisasi data gaji dan umur menggunakan MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

Cross Validation

In [ ]:
# membuat model Decision Tree
dt = DecisionTreeClassifier()

# melakukan 5-fold cross validation
scores = cross_val_score(dt, X_train, y_train, cv=5)

# menampilkan hasil cross validation
print('Hasil cross validation:', scores)

Hasil cross validation: [0.84375  0.921875 0.8125   0.859375 0.890625]